#!/bin/bash
# By chris1111
# Version "1.0" Geforce Kepler patcher# Base on jackluke work
PARENTDIR=$(dirname "$0")
cd "$PARENTDIR"

sudo cp -R ./*.kext /Volumes/Monterey-DISK/System/Volumes/Update/mnt1/System/Library/Extensions
Sleep 1
sudo cp -R ./*.bundle /Volumes/Monterey-DISK/System/Volumes/Update/mnt1/System/Library/Extensions
Sleep 1
sudo cp -R /Private/tmp/*.kext /Volumes/Monterey-DISK/System/Volumes/Update/mnt1/System/Library/ExtensionsSleep 1sudo cp -R ./*.bundle /Volumes/Monterey-DISK/System/Volumes/Update/mnt1/System/Library/ExtensionsSleep 1sudo cp -R ./WebKit.framework /Volumes/Monterey-DISK/System/Volumes/Update/mnt1/System/Library/FrameworksSleep 1sudo cp -R ./OpenCL.framework /Volumes/Monterey-DISK/System/Volumes/Update/mnt1/System/Library/FrameworksSleep 1sudo cp -R ./AppleGVA.framework /Volumes/Monterey-DISK/System/Volumes/Update/mnt1/System/Library/PrivateFrameworksSleep 1sudo cp -R ./AppleGVACore.framework /Volumes/Monterey-DISK/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks


echo "Kext Cache repair! Please wait. ."
sudo chown -R root:wheel /System/Volumes/Update/mnt1/System/Library/Extensions
sudo chmod -R 755 /System/Volumes/Update/mnt1/System/Library/Extensions
sudo kmutil install --volume-root /System/Volumes/Update/mnt1/ --update-all
sudo bless --folder /System/Volumes/Update/mnt1/System/Library/CoreServices --bootefi --create-snapshot

echo "Done"


