#!/bin/bash
# Version "1.1" Patch HD4000 Monterey chris1111# Base on jackluke work
# Vars
apptitle="Patch HD4000 Monterey"
version="1.1"
# Set Icon directory and file 
export ICNS=$(dirname "${0}")
iconfile="$ICNS/AppIcon.icns"
echo "Starting patch HD 4000"
Sleep 2

echo "Verification SIP"
Sleep 2
function vertifySIP {
	echo -n "Verification SIP..."
	if [[ "$(csrutil status | grep "System Integrity Protection status: disabled." | wc -l)" == "       0" && "$(csrutil status | grep "Filesystem Protections: disabled" | wc -l)" == "       0" ]]; then
		echo ""
osascript -e 'tell app "System Events" to display dialog "SIP is enabled on this system. Please disable the SIP from the bootloader or boot to Recovery HD or an install USB drive, open a new terminal window and enter (csrutil disable), and (csrutil authenticated-root disable) without parentheses.
Once done, reboot into your standard installation of macOS and run this program again." with icon file "System:Library:CoreServices:CoreTypes.bundle:Contents:Resources:FileVaultIcon.icns" buttons {"OK"} default button 1 with title "HD4000 Monterey (Error SIP Enable)"'

osascript -e 'display notification "Program close" sound name "default" with title "'"$apptitle"'" subtitle "SIP Enable"'
echo "QUITAPP"
exit 0
		return 1
	fi
	return 0		
		
}

vertifySIP

echo "Verification SIP"
Sleep 2
function vertifySIP {
	echo -n "Verification SIP..."
	if [[ "$(csrutil authenticated-root status | grep "System Integrity Protection status: disabled." | wc -l)" == "       0" && "$(csrutil authenticated-root status | grep "Authenticated Root status: disabled" | wc -l)" == "       0" ]]; then
		echo ""
osascript -e 'tell app "System Events" to display dialog "SIP authenticated-root is enabled on this system. Please disable the SIP from the bootloader or boot to Recovery HD or an install USB drive, open a new terminal window and enter (csrutil disable), and (csrutil authenticated-root disable) without parentheses.
Once done, reboot into your standard installation of macOS and run this program again." with icon file "System:Library:CoreServices:CoreTypes.bundle:Contents:Resources:FileVaultIcon.icns" buttons {"OK"} default button 1 with title "HD4000 Monterey (Error SIP authenticated-root Enable)"'

osascript -e 'display notification "Program close" sound name "default" with title "'"$apptitle"'" subtitle "SIP Enable"'
echo "QUITAPP"
exit 0
		return 1
	fi
	return 0		
		
}

vertifySIP

Sleep 1

Open ./PatchHD4000.app
echo "QUITAPP"

